/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoB;
import PantallaPrincipal.Menu;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Cristian Rojas
 */
public class PuntoB extends javax.swing.JFrame {

    public double[] vec;
    public int num, inter;

    public int getInter() {
        return inter;
    }

    public void setInter(int inter) {
        this.inter = inter;
    }

    public int getNum() {
        return num;
    }

    public void setNum(int num) {
        this.num = num;
    }

    public double[] getVec() {
        return vec;
    }

    public void setVec(double[] vec) {
        this.vec = vec;
    }
    
    /**
     * Creates new form PuntoB
     */
    public PuntoB() {
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent evt){
                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del Sistema?","ADVERTENCIA",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {                   
                System.exit(0);
            }               
        }});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtCantNum = new javax.swing.JTextField();
        jbtnIniciar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jtxtCantIntervalos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaDatos = new javax.swing.JTextArea();
        jbtnTabla = new javax.swing.JButton();
        jbtnHistograma = new javax.swing.JButton();
        jbtnVolver = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        jLabel1.setText("Metodo Random");

        jLabel2.setText("Ingrese Cantidad de Numeros:");

        jtxtCantNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCantNumKeyTyped(evt);
            }
        });

        jbtnIniciar.setText("Generar");
        jbtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarActionPerformed(evt);
            }
        });

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jtxtCantIntervalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantIntervalosActionPerformed(evt);
            }
        });
        jtxtCantIntervalos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCantIntervalosKeyTyped(evt);
            }
        });

        jLabel3.setText("Ingrese Cantidad de Intervalos:");

        jLabel4.setText("Serie Aleatoria");

        jtxtAreaDatos.setColumns(20);
        jtxtAreaDatos.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaDatos);

        jbtnTabla.setText("Ver tabla");
        jbtnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTablaActionPerformed(evt);
            }
        });

        jbtnHistograma.setText("Ver histograma");
        jbtnHistograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHistogramaActionPerformed(evt);
            }
        });

        jbtnVolver.setText("Volver");
        jbtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVolverActionPerformed(evt);
            }
        });

        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtCantNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtCantIntervalos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbtnTabla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnHistograma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCantNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jbtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCantIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCantNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantNumKeyTyped
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada

        if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {//Si el caracter ingresado es una letra
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }

        if (k == 241 || k == 209) {//Si el caracter ingresado es una letra
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }

        if (k == 10) {//si se presiona enter
            //transfiere el foco
            jtxtCantNum.transferFocus();
        }
    }//GEN-LAST:event_jtxtCantNumKeyTyped

    
    private void jbtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarActionPerformed
        // TODO add your handling code here:
        try{
            jtxtAreaDatos.setText(null);
            DecimalFormat RedondearADos = new DecimalFormat("0.0000");
            int a = Integer.parseInt(jtxtCantNum.getText());
            num = a;
            int c = Integer.parseInt(jtxtCantIntervalos.getText());
            inter = c;
            if(inter>29){
                JOptionPane.showMessageDialog(rootPane, "Máx. 29 intervalos.", "Validando Datos", WIDTH);
                return;
            }
            if(inter<1){
                JOptionPane.showMessageDialog(rootPane, "Mín. 1 intervalo.", "Validando Datos", WIDTH);
                return;
            }
            double b;
            double esp = (a/c);
            if(a<1){
                JOptionPane.showMessageDialog(rootPane, "Cantidad de numeros tiene que ser mayor o igual a 1", "Validando Datos", WIDTH);
                return;
            }
            if(c<1){
                JOptionPane.showMessageDialog(rootPane, "Mín. 1 intervalos", "Validando Datos", WIDTH);
                return;
            }
            vec = new double[a];
            Random rnd = new Random();
            long startTime = System.currentTimeMillis();
            for (int i = 0; i < a; i++) {
                b = rnd.nextDouble();
                vec[i] = b;
                jtxtAreaDatos.append(RedondearADos.format(b) + "\n");
            }
            /*
            13.4s
            for (int i = 0; i < list.size(); i++) {
                aux += list.get(i);
            }*
            /* 14 segundos
            String[] stringArray = list.toArray(new String[0]);
            /*for(String nro: stringArray){
                aux += nro;
            }*/
            //long endTime = System.currentTimeMillis() - startTime;
            //jtxtAreaDatos.setText(aux);
            //System.out.println(endTime);
        }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "No se ingresaron los datos", "Validando Datos", WIDTH);
        }
    }//GEN-LAST:event_jbtnIniciarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        jtxtCantNum.setText(null);
        jtxtCantIntervalos.setText(null);
        jtxtAreaDatos.setText(null);
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jtxtCantIntervalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantIntervalosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantIntervalosActionPerformed

    private void jtxtCantIntervalosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantIntervalosKeyTyped
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada

        if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {//Si el caracter ingresado es una letra
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }

        if (k == 241 || k == 209) {//Si el caracter ingresado es una letra
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }

        if (k == 10) {//si se presiona enter
            //transfiere el foco
            jtxtCantIntervalos.transferFocus();
        }
    }//GEN-LAST:event_jtxtCantIntervalosKeyTyped

    private void jbtnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTablaActionPerformed
        // TODO add your handling code here:
        try{
            int b = Integer.parseInt(jtxtCantIntervalos.getText());
            int a = Integer.parseInt(jtxtCantNum.getText());
            Tabla tuFrame = new Tabla(this);
            tuFrame.setVisible(true);
            setLocationRelativeTo(null);
        }catch(NumberFormatException | ClassCastException | NullPointerException e){
            JOptionPane.showMessageDialog(rootPane, "No se ingresaron los datos", "Error Tabla", WIDTH);
        }
    }//GEN-LAST:event_jbtnTablaActionPerformed

    private void jbtnHistogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHistogramaActionPerformed
        // TODO add your handling code here:
        try{
            int b = Integer.parseInt(jtxtCantIntervalos.getText());
            inter = b;
            Histograma histo = new Histograma("Histograma", vec, b);
            histo.pack();
            RefineryUtilities.centerFrameOnScreen(histo);
            histo.setVisible(true);
        }
        catch(NumberFormatException | ClassCastException e){
            JOptionPane.showMessageDialog(rootPane, "No se ingresaron los datos", "Error Histograma", WIDTH);
        }
    }//GEN-LAST:event_jbtnHistogramaActionPerformed

    private void jbtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_jbtnVolverActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del Sistema?","ADVERTENCIA",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuntoB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PuntoB().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnHistograma;
    private javax.swing.JButton jbtnIniciar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnTabla;
    private javax.swing.JButton jbtnVolver;
    private javax.swing.JTextArea jtxtAreaDatos;
    private javax.swing.JTextField jtxtCantIntervalos;
    private javax.swing.JTextField jtxtCantNum;
    // End of variables declaration//GEN-END:variables
}
