/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoB;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian Rojas
 */
public class Tabla extends javax.swing.JFrame {

    PuntoB frame; //la variable de instancia del JFrame
    int num;// Cantidad de numeros
    int inter;// cantidad de intervalos
    double fesp;// frecuencia esperada
    double vec[];// vector de rnd
    int cont[];//frecuencia observada
    double cont2[];
    double dif[];//diferencia cuadrada para chi  "(Fobs - Fesp)2"
    double difdiv[];//[(Fobs - Fesp)2]/Fesp
    String valInt[];
    double chi[];
    
    DefaultTableModel datos;
    
    /**
     * Creates new form Tabla
     * @param frame
     */
    public Tabla(PuntoB frame) {
        this.frame = frame;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        num = frame.getNum();
        inter = frame.getInter();
        vec = frame.getVec();
        datos = new DefaultTableModel(new Object[]{"N°", "Intervalo", "Fobs", "Fesp", "(Fobs - Fesp)^2", "[(Fobs - Fesp)^2]/Fesp"}, 0);
        calcularValores();
        rellenarTablas();
        jTablaChi.setModel(datos);
        txt_gradolibertad.setText(Integer.toString(inter-1));
        txt_gradolibertad.setEnabled(false);
        txt_chitabulado.setEnabled(false);
        txt_confianza.setEnabled(false);
        
        chi=new double[30];
        chi[0]=3.8;
        chi[1]=6;
        chi[2]=7.8;
        chi[3]=9.5;
        chi[4]=11.1;
        chi[5]=12.6;
        chi[6]=14.1;
        chi[7]=15.5;
        chi[8]=16.9;
        chi[9]=18.3;
        chi[10]=19.7;
        chi[11]=21;
        chi[12]=22.4;
        chi[13]=23.7;
        chi[14]=25;
        chi[15]=26.3;
        chi[16]=27.6;
        chi[17]=28.9;
        chi[18]=30.1;
        chi[19]=31.4;
        chi[20]=32.7;
        chi[21]=33.9;
        chi[22]=35.2;
        chi[23]=36.4;
        chi[24]=37.7;
        chi[25]=38.9;
        chi[26]=40.1;
        chi[27]=41.3;
        chi[28]=42.6;
        chi[29]=43.8;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbtn_calcular = new javax.swing.JButton();
        txt_chitabulado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaChi = new javax.swing.JTable();
        jtxtChi = new javax.swing.JTextField();
        txt_gradolibertad = new javax.swing.JTextField();
        txt_confianza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtn_calcular.setText("Calcular");
        jbtn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_calcularActionPerformed(evt);
            }
        });

        jLabel4.setText("Chi Cuadrado Tabulado:");

        jTablaChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaChi);
        if (jTablaChi.getColumnModel().getColumnCount() > 0) {
            jTablaChi.getColumnModel().getColumn(0).setResizable(false);
            jTablaChi.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jtxtChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChiActionPerformed(evt);
            }
        });

        txt_gradolibertad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gradolibertadActionPerformed(evt);
            }
        });

        txt_confianza.setText("0.95");

        jLabel3.setText("Confianza:");

        jLabel2.setText("Grados de Libertad:");

        jLabel1.setText("Chi Cuadrado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtChi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_gradolibertad))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(txt_confianza)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_chitabulado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_chitabulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_gradolibertad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_confianza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_calcularActionPerformed
        // TODO add your handling code here:
        double valor;
        valor=chi[Integer.parseInt(txt_gradolibertad.getText())-1];
        txt_chitabulado.setText(String.valueOf(valor));
        txt_chitabulado.setForeground(Color.red);
        txt_chitabulado.setBackground(Color.blue);
        txt_confianza.setForeground(Color.red);
        txt_confianza.setBackground(Color.blue);
        txt_gradolibertad.setForeground(Color.red);
        txt_gradolibertad.setBackground(Color.blue);
    }//GEN-LAST:event_jbtn_calcularActionPerformed

    private void jtxtChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChiActionPerformed

    private void txt_gradolibertadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gradolibertadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gradolibertadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaChi;
    private javax.swing.JButton jbtn_calcular;
    private javax.swing.JTextField jtxtChi;
    private javax.swing.JTextField txt_chitabulado;
    private javax.swing.JTextField txt_confianza;
    private javax.swing.JTextField txt_gradolibertad;
    // End of variables declaration//GEN-END:variables
    
    private void calcularValores(){
        cont= new int[inter];// cantidad de valores de acuerdo al intervalo
        dif = new double[inter];// diferencia del chi x intervalo
        
        difdiv = new double[inter];
        
        double cte = (1.0000/inter);
        fesp = (double) num/inter;
        valInt = new String[inter];
        DecimalFormat RedondearADos = new DecimalFormat("0.0000");
        
        double intfinal = 0.0000;
        double intinicial;
        for (int i = 0; i < inter; i++) {
            intinicial = intfinal;//inicia el limite izq de cada linea
           
            intfinal = (intinicial + cte);//inicial el limite derecho de cada linea
            valInt[i] = RedondearADos.format(intinicial)+" - "+RedondearADos.format(intfinal);

            for (int j = 0; j < vec.length; j++) {//recorre los valores del rnd
                if (vec[j] >= intinicial && vec[j] < intfinal) {//ubica de acuerdo al intervalo               
                    cont[i]++;//cuenta
                }
            }

        }
        for (int i = 0; i < cont.length; i++) {// cacula el cuadrado
            dif[i] = Math.pow((cont[i] - fesp),2);
            difdiv[i]= (dif[i]/fesp);
        }
     
        double acu = 0;
        for (int i = 0; i < dif.length; i++) {
            acu += dif[i];
        }
        //System.out.println(acu);
        double chi_cuadrado = acu / fesp;
        jtxtChi.setText(RedondearADos.format(chi_cuadrado));
        
    }

    private void rellenarTablas(){
        DecimalFormat RedondearADos = new DecimalFormat("0.0000");
        for(int i=0;i<inter;i++){
            Object[] fila = new Object[6];
            fila[0]=i;
            fila[1]=valInt[i];
            fila[2]=cont[i];
            fila[3]=RedondearADos.format(fesp);
            fila[4]=RedondearADos.format(dif[i]);
            fila[5]=RedondearADos.format(difdiv[i]);
            datos.addRow(fila);
        }
    }
}
